ax1=gca;
ax2 = axes('Position',get(ax1,'Position'),...
    'XAxisLocation','top',...
    'YAxisLocation','right',...
    'Color','none',...
    'XColor','k','YColor','k');
set(ax2,'ylim',get(ax1,'ylim'))
set(ax2,'ydir','reverse')
set(ax2,'xlim',get(ax1,'xlim'))
set(ax1,'xlim',get(ax1,'xlim'))
grid