function List=GetStaNames(Component)
% GetStaNames.m
%
% GETSTANAMES: Get the names of the station sorted by latitude.
%
%	Syntaxis
%		List=GetStaNames('Component');
%		List=GerStaNames(Index);
%
%	IN: 
%		Component ('N', 'E' or 'Z');.
%		Index Array generated by GenIndexSta()	
%
%	OUT: 
%		An array of Nx4 with the name of N stations.
%
%	Author:
%		Luis A. Dominguez. 2007
%

if nargin==0
    Component='Z';
end

[files N]=ValidateComponent(Component);
Index=IndexGenDst(Component);
NumFiles=length(files);
% TODO

if strcmp(Component,'all')
    List=char(32.*ones(100,4));
    if strcmp(getenv('OS'),'Windows_NT')
        fid=fopen('C:\MATLAB7\work\MASE_files\stations_name_lat.txt');
    else
        fid=fopen('/home/antonio/mat_work/MASE_files/stations_name_lat.txt');
    end
     
    % Populating list
    for i=1:100 % One hundred seismic stations
        List(i,:)=fgetl(fid);
    end
    [deltas I]=GenDeltas('all');
    List=List(I,:);
    fclose(fid)
    return
end

List=char(32.*ones(NumFiles,4));
for ii=1:NumFiles
    full_name=fullfile(pwd,files(ii).name); 
    s=rsac(full_name);
    name=s.kstnm;
    %[p name]=readheader(full_name);
    n=length(name);
	List(find(Index==ii),1:n)=name;
end

end

